//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SmartAssistance.Module.BusinessObjects.Prueba22
{

    public partial class Assistence : XPObject
    {
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        Module fModule;
        public Module Module
        {
            get { return fModule; }
            set { SetPropertyValue<Module>(nameof(Module), ref fModule, value); }
        }
        DateTime fLastModifiedDate;
        public DateTime LastModifiedDate
        {
            get { return fLastModifiedDate; }
            set { SetPropertyValue<DateTime>(nameof(LastModifiedDate), ref fLastModifiedDate, value); }
        }
        [Association(@"StudentAssistenceReferencesAssistence")]
        public XPCollection<StudentAssistence> StudentAssistences { get { return GetCollection<StudentAssistence>(nameof(StudentAssistences)); } }
    }

}
