//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SmartAssistance.Module.BusinessObjects.Prueba22
{

    public partial class StudentAssistence : XPObject
    {
        Student fStudent;
        public Student Student
        {
            get { return fStudent; }
            set { SetPropertyValue<Student>(nameof(Student), ref fStudent, value); }
        }
        Assistence fAssistence;
        [Association(@"StudentAssistenceReferencesAssistence")]
        public Assistence Assistence
        {
            get { return fAssistence; }
            set { SetPropertyValue<Assistence>(nameof(Assistence), ref fAssistence, value); }
        }
    }

}
