//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SmartAssistance.Module.BusinessObjects.Prueba22
{

    public partial class Warning : XPObject
    {
        Student fStudent;
        public Student Student
        {
            get { return fStudent; }
            set { SetPropertyValue<Student>(nameof(Student), ref fStudent, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        Module fModule;
        public Module Module
        {
            get { return fModule; }
            set { SetPropertyValue<Module>(nameof(Module), ref fModule, value); }
        }
    }

}
